auth_enabled: false
server:
  http_listen_port: 3100
common:
  instance_addr: 127.0.0.1
  ring:
    instance_addr: 127.0.0.1
    kvstore: { store: inmemory }
  path_prefix: /loki
schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks
limits_config:
  retention_period: 168h
chunk_store_config:
  max_look_back_period: 168h
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
