host = ".51"
interval = "30s"

[[checks]]
type = "Http"
name = "pihole-api"
url = "http://127.0.0.1/admin/api.php?summary"
expect_status = 200
notify_recovery = true
remediation = [{ action = "command", cmd = "sudo systemctl restart pihole-FTL.service" }]

[[checks]]
type = "Http"
name = "status-pizza"
url = "https://status.pizza/"
expect_status = 200
notify_recovery = true
remediation = [{ action = "command", cmd = "docker restart caddy || true" }]
