host = ".60"
interval = "30s"

[[checks]]
type = "Http"
name = "status-pizza"
url = "https://status.pizza/"
expect_status = 200
notify_recovery = true
remediation = [{ action = "command", cmd = "docker restart caddy || true" }]

[[checks]]
type = "Http"
name = "kuma-local"
url = "http://127.0.0.1:3001/"
expect_status = 200
notify_recovery = true
remediation = [{ action = "command", cmd = "docker restart uptime-kuma || true" }]
