[monitoring]
monitoring01 ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[targets]
ubuntu-docker ansible_host=192.168.2.51 ansible_user=tim ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=/home/tim/.ssh/ansible_monitoring01
nextcloud ansible_host=192.168.2.60 ansible_user=tim ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=/home/tim/.ssh/ansible_monitoring01
